/*
 * THIS PROVIDES FOR EXACTLY ONSTANCES OF DISPLAYTYPES.
 * AN ENUM TYPWE HAS A FIXED NUMBER OF BAMED INSNTANCES
 *
 * THESE ARE DispllayType OBJECTS, NOT STRINGS
 * THEY ARE REFERENCED AS '
 *      DISPLAYTYPE.LED
 *      DISPLAYTYPE.CRT .....ETC
 */
enum DisplayType {
        LED, OLED, PLASMA, LCD, CRT

}
